# Prediksi Berat Badan

In [28]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
import joblib

In [29]:
df = pd.read_csv("datasets/weight-height.csv")
df.head()

Gender     Weight      Height
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

## Labeling Atribut

In [30]:
df.Gender = LabelEncoder().fit_transform(df.Gender)
df.head()

Gender     Weight      Height
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [31]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns='Weight'), df.Weight, test_size=0.2, random_state=50)
model = LinearRegression().fit(X_train, y_train)
y_pred = model.predict(X_test)

In [40]:
model.predict([[0,160]])

array([66.6991246])

In [41]:
y_test[:5]

array([64.42902169, 62.21122824, 66.80124098, 73.7421446 , 66.79214738])

In [36]:
y_pred[:5]

array([63.08437376, 63.76427294, 67.55253735, 70.57053579, 64.5842611 ])

In [37]:
model.score(X_test, y_test)*100

85.76866287912456

## Menyimpan Model

In [38]:
joblib.dump((model), "prediksi-BB.pkl")

['prediksi-BB.pkl']